### ISSUE TITLE
Instagram-web version 0.99-1 only allows adding one photo per post

### ISSUE THREAD

**Issue by serial02** [ray1422/instagram-web#1]
Hello

The Instagram-web application on the desktop is great, but I would like to know how to put more than one photo per post?

Does the application only allow one image at a time?

Instagram-web version 0.99-1 only allows adding one photo per post

![Captura de Tela_20200304201907](https://user-images.githubusercontent.com/32621790/75932162-87b15b80-5e55-11ea-90e6-c8ba18a32a31.png)

![Captura de Tela_20200304201918](https://user-images.githubusercontent.com/32621790/75932220-ab74a180-5e55-11ea-86a0-53039da664c9.png)

Thanks in advance for your attention

Edson

**Comment by ray1422** [comment]
This program is just a wrapper of a browser with user-agent to make instagram show mobile layout.
